# Generated by Django 5.1.2 on 2024-10-31 22:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('telefono', models.JSONField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('comision', models.JSONField()),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'db_table': 'FormaPago',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('ubicacion', models.JSONField()),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
                'db_table': 'Local',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_realizado', models.DateField()),
                ('fecha_recibido', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'Permiso',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Reduccion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('tarifa', models.JSONField()),
            ],
            options={
                'verbose_name': 'Reducción',
                'verbose_name_plural': 'Reducciones',
                'db_table': 'Reduccion',
            },
        ),
        migrations.CreateModel(
            name='TarifaIVA',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tarifa', models.JSONField()),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tarifa IVA',
                'verbose_name_plural': 'Tarifas IVA',
                'db_table': 'TarifaIVA',
            },
        ),
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('correo', models.TextField()),
                ('clave', models.TextField()),
                ('estado', models.BooleanField()),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.empleado')),
            ],
            options={
                'verbose_name': 'Credencial',
                'verbose_name_plural': 'Credenciales',
                'db_table': 'Credencial',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField()),
                ('fecha_terminacion', models.DateField()),
                ('fecha_final', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad_pago', models.DurationField()),
                ('estado', models.BooleanField()),
                ('cargo', models.ForeignKey(db_column='id_cargo', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.cargo')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.empleado')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.empleado')),
                ('local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.local')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envios',
                'db_table': 'Envio',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_IVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.cliente')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.empleado')),
                ('forma_pago', models.ForeignKey(db_column='id_forma_pago', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.formapago')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.contrato')),
            ],
            options={
                'verbose_name': 'Nomina',
                'verbose_name_plural': 'Nominas',
                'db_table': 'Nomina',
            },
        ),
        migrations.CreateModel(
            name='DetallePermiso',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.empleado')),
                ('permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.permiso')),
            ],
            options={
                'verbose_name': 'Detalle de Permiso',
                'verbose_name_plural': 'Detalles de Permiso',
                'db_table': 'DetallePermiso',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.pedido')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'db_table': 'DetallePedido',
            },
        ),
        migrations.CreateModel(
            name='DetalleLocal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('local', models.ForeignKey(db_column='id_local', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.local')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Local',
                'verbose_name_plural': 'Detalles de Local',
                'db_table': 'DetalleLocal',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.factura')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'DetalleFactura',
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('envio', models.ForeignKey(db_column='id_envio', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.envio')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Envío',
                'verbose_name_plural': 'Detalles de Envio',
                'db_table': 'DetalleEnvio',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.proveedor'),
        ),
        migrations.CreateModel(
            name='DetalleReduccion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nomina', models.ForeignKey(db_column='id_nomina', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.nomina')),
                ('reduccion', models.ForeignKey(db_column='id_reduccion', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.reduccion')),
            ],
            options={
                'verbose_name': 'Detalle de Reducción',
                'verbose_name_plural': 'Detalles de Reducción',
                'db_table': 'DetalleReduccion',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9615f4a5-8783-4fab-b1ab-562343aa2699'), editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicial', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('estado', models.BooleanField()),
                ('crendencial', models.ForeignKey(db_column='id_crendencial', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.credencial')),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'Sesion',
            },
        ),
        migrations.CreateModel(
            name='PrecioVentaProducto',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.JSONField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicial', models.DateField()),
                ('fecha_final', models.DateField()),
                ('estado', models.BooleanField()),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.producto')),
                ('tarifa_IVA', models.ForeignKey(db_column='id_tarifa_IVA', on_delete=django.db.models.deletion.CASCADE, to='sistema_transaccional.tarifaiva')),
            ],
            options={
                'verbose_name': 'Precio de Venta de Producto',
                'verbose_name_plural': 'Precios de Venta de Producto',
                'db_table': 'PrecioVentaProducto',
            },
        ),
    ]
