services:
  cafe_coloriginal:
    working_dir: /usr/cafe_coloriginal
    build: .
    container_name: cafe_coloriginal
    command:
      - /bin/bash
      - -c
      - |
        test -f sistema_transaccional/migrations/0001_initial.py && rm sistema_transaccional/migrations/0001_initial.py
        python manage.py migrate
        python manage.py makemigrations
        python manage.py sqlmigrate sistema_transaccional 0001 > script_db.psql
        python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/cafe_coloriginal
      - ${APP_TEMP_DIR}:/tmp/cafe_coloriginal.session